name: manual deploy

on:  
  workflow_dispatch:
    inputs:
      GIT_BRANCH:
        description: 'branch to clone'     
        required: true
        default: 'master'

jobs: 
  main:
    runs-on: ubuntu-latest
    env:
      REPO_TO_FETCH: "github.com/atex-polopoly/dns-romeo.git"
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_PASSWORD: ${{ secrets.GH_PASSWORD }}
      CONVOX_TOKEN: ${{ secrets.CONVOX_TOKEN }}

    steps:
      - name: checkout
        run: |
          git config --global http.sslverify false
          git clone --branch ${{ github.event.inputs.GIT_BRANCH}} https://$GH_USERNAME:$GH_PASSWORD@$REPO_TO_FETCH _
          cd _
          ls -la

      - name: install convox cli
        run: |
          curl -L https://github.com/convox/convox/releases/latest/download/convox-linux -o /tmp/convox
          mv /tmp/convox /usr/local/bin/convox
          chmod 755 /usr/local/bin/convox
          convox version

      - name: deploy
        run: |
          echo "login into convox cli"
          convox login console.convox.com -t $CONVOX_TOKEN
          echo "switch rack"
          convox switch atex-development/atex-dev
          echo "deploy"
          convox deploy --app romeo-dev
