name: manual deploy

on:  
  workflow_dispatch:
    inputs:
      GIT_BRANCH:
        description: 'branch to clone'     
        required: true
        default: 'master'

jobs: 
  main:
    runs-on: ubuntu-latest
    env:
      REPO_TO_FETCH: "github.com/atex-polopoly/dns-romeo.git"
      REPO2_TO_FETCH: "github.com/atex-polopoly/desk-node-server.git"
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_PASSWORD: ${{ secrets.GH_PASSWORD }}
      CONVOX_TOKEN: ${{ secrets.CONVOX_TOKEN }}

    steps:
      - name: install nvm
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: 10
      - run: |
          node -v
      

      - name: checkout dns-romeo
        run: |
          git config --global http.sslverify false
          git clone --branch ${{ github.event.inputs.GIT_BRANCH}} https://$GH_USERNAME:$GH_PASSWORD@$REPO_TO_FETCH dns-romeo
          cd dns-romeo
          ls -la
          npm install
          npm run build
          ls -la dist/

      - name: checkout desk-node-server
        run: |
          git config --global http.sslverify false
          git clone --branch ${{ github.event.inputs.GIT_BRANCH}} https://$GH_USERNAME:$GH_PASSWORD@github.com/atex-polopoly/desk-node-server.git desk-node-server
          cd desk-node-server
          ls -la
          mkdir romeo/
          cp -r -f -v ../dns-romeo/dist/* ./romeo
          ls -la romeo/


      - name: install convox cli
        run: |
          curl -L https://github.com/convox/convox/releases/latest/download/convox-linux -o /tmp/convox
          mv /tmp/convox /usr/local/bin/convox
          chmod 755 /usr/local/bin/convox
          convox version


      - name: deploy
        run: |
          cd dns-romeo
          echo "login into convox cli"
          convox login console.convox.com -t $CONVOX_TOKEN
          convox racks          
          echo "switch rack"
          convox switch atex-development/atex-dev
          echo "list apps"
          convox apps
          echo "deploy"
          exit 1
          convox deploy --app romeo-dev
      #     # cd dns-romeo
      #     # chmod +x launch.sh
      #     # ./launch.sh
